### ISSUE TITLE
Unnecessary tokens inclusion, incorrect Sass reference

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-alert#75]
### Please verify the version of auro-alert you have installed

@latest

### Please describe the bug

See the following code: 

https://github.com/AlaskaAirlines/auro-alert/blob/25896a936a3f667b501a5ef5c9138c2430e6a78c/src/style.scss#L8

Importing `SassCustomProperties` into the src CSS for the element is not required. This will create a local reference that will override externally set tokens and theme settings. 

https://github.com/AlaskaAirlines/auro-alert/blob/25896a936a3f667b501a5ef5c9138c2430e6a78c/src/style.scss#L27

Non-interpolated Sass references will output a direct string of the Sass variable. 

```css
[auro-icon] {
  --ds-auro-icon-size: var(--ds-size-300, $ds-size-300);
  margin-right: var(--ds-size-100, 0.5rem);
}
```

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

The unnecessary import should be removed to reduce local scope and file size. 

The Sass variable should be interpolated so that the output CSS will be a color value, not a string of the Sass variable. 

### Additional context

n/a
